### ISSUE TITLE
fixes for 256 color terminal

### ISSUE THREAD

**Issue by y** [ciaranm/inkpot#1]
When using 256 color terminal, 'set bg?' shows background has been reset to light due to a bug in vim. Setting background to dark again after the highlighting has been changed fixes this. See https://github.com/KevinGoodsell/vim-color-check/blob/master/color-scheme-recommendations.txt and the same author has a patch for some other issues:
https://github.com/KevinGoodsell/vim-xterm-colors/blob/master/patches/inkpot.vim.diff

**Comment by ciaranm** [comment]
I'm not sure what you're trying to do there. You just deleted the 256 colour support...

**Comment by y** [comment]
I thought the first sentence was clear. I set bg=dark in my .vimrc, use inkpot as my colorscheme (which also set bg=dark), but when I check bg after the colorscheme has loaded, it is now set to light, instead of dark. That is not good.

The explanation of the bug is given by the same guy here https://github.com/KevinGoodsell/vim-color-check/blob/master/color-scheme-recommendations.txt#L130 and here http://www.reddit.com/r/vim/comments/f0a2p/neverlandvim_all_colorschemes_suck_256_colors/c1cbxu1 .

**Comment by ciaranm** [comment]
The solution is to fix Vim, then, not try to work around it in every single colour scheme.
