### ISSUE TITLE
CoffeeScript Mistakes

### ISSUE THREAD

**Issue by ecoleman** [ciaranm/inkpot#3]
In CoffeeScript files, parenthesis as well as commas are getting the text background, you can see here: http://colemando.com/inkpot.png

**Comment by ciaranm** [comment]
That's something the CoffeeScript syntax files define, not something Inkpot handles. Vim colour schemes don't define colours for syntax-specific things -- they define colours for general concepts, and then syntax files say how syntax is to be shown using a general concept.
